name: master
channels:
  - conda-forge
dependencies:
  - ipykernel
  - pandas
  - numpy
  - scipy
  - opencv
  - pytorch
  - transformers[torch]
  - evaluate
  - tqdm                                  
  - torchvision
  - matplotlib
  # - datasets
  - pillow
  - pip
  - pip:
    - xformers
    - accelerate -U