name: master
channels:
  - conda-forge
dependencies:
  - ipykernel
  - pandas
  - numpy
  - scipy
  - opencv
  - transformers[torch]
  - evaluate
  - tqdm
  - matplotlib
  - datasets
  - pillow
  - pip 
  - pip:
    - xformers
    - accelerate