name: master
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - ipykernel
  - pandas
  - numpy
  - scipy
  - opencv
  - transformers[torch]
  - evaluate
  - tqdm
  - matplotlib
  - datasets
  - pillow
  - pytorch=11.7
  - torchvision
  - torchaudio
  - pip 
  - pip:
    - xformers
    - accelerate